'''
Program: Screens.py
Author : Quang Hoang
Date   : 2019-10-07
Synopis: This contain all the screens
'''

def about():
    print("")
    print("********************************************************************************")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*				Enigma Machine                                 *")
    print("*                                                                              *")
    print("*                            For when you have                                 *")
    print("*                            something that needs                              *")
    print("*                            hiding or cracking!                               *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                    Programmers: CIS220 Class Fall 2019                       *")
    print("*                                                                              *")
    print("*                           Press Enter to continue                            *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("********************************************************************************")
    sel = input("")
    import screen_MAIN
    screen_MAIN.getOption("Home")
    return sel

def home():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("				  Enigma Machine")
    print("")
    print("")
    print("")			   	      
    print("                         Welcome to the Enigma Machine!")
    print("                         This is the software version of")
    print("                         the Enigma Machine used in WWII.")
    print("                         Choose your options below to try.")
    print("")
    print("")
    print("")
    print("                     Encryption [1]             Decryption [2]")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel

def menu():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("				  Enigma Machine")
    print("")
    print("")
    print("			   	       Menu ")
    print("")
    print("				 Home		1")
    print("				 Encryption 	2")
    print("				 Decryption	3")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel

def setting():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("				  Enigma Machine")
    print("")
    print("")
    print("			   	      Setting ")
    print("")
    print("			    Change Plug Board	    1")
    print("			    Change Key		    2")
    print("					")
    print("					")
    print("						")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel

def settingPlugBoard():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("				  Enigma Machine")
    print("")
    print("")
    print("			   	    Plug Board")
    print("				")
    print("		     To change your Plug Board please enter ")
    print("		     your new Plug Board name at the bottom. ")
    print("			    ")
    print("			Thank You    ")
    print("			    ")
    print("					")
    print("					")
    print("						")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Enter your new Plug Board name here: ")
    return sel

def settingKey():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("				  Enigma Machine")
    print("")
    print("")
    print("			   	        Key")
    print("				         ")
    print("		               Enter your key below")
    print("			    ")
    print("			    ")
    print("			    ")
    print("					")
    print("					")
    print("						")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Enter Key:    ")
    return sel

def helpScr():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("				  Enigma Machine")
    print("")
    print("")
    print("			   	      Help ")
    print("")
    print("			   Help instructions will be up soon.")
    print("			   Sorry for any inconvenient.")
    print("            ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel


def encryptionKey():
    
    from generateKey import getKey
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("				  Enigma Machine")
    print("")
    print("")
    print("			   	    Encryption ")
    print("")
    print("                   Enter your key or hit Enter to generate key")
    print("		       ")
    print("            ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    key = input("Enter Key:  ")
    
    if key == '':
        key = getKey()
    xkey = ''
    for i in key:
        xkey = xkey + str(i)
    key = xkey    
    return key

def encryption():
    key = encryptionKey()
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("				  Enigma Machine")
    print("")
    print("")
    print("			   	    Encryption ")
    print("")
    print("                             Enter your message below")
    print("                                    Key:  {}".format(key))
    print("")
    print("            ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Enter Message:  ")
    return sel

def decryption():
    key = settingKey()
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("				  Enigma Machine")
    print("")
    print("")
    print("			   	    Decryption ")
    print("")
    print("                           Enter your message below")
    print("                                  Key:  {}".format(key))
    print("")
    print("            ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Enter Message:  ")

    return sel
