'''
Program: Screens.py
Author : Quang Hoang
Date   : 2019-10-07
Synopis: This contain all the screens
'''


def about():
    print("")
    print("********************************************************************************")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*				Enigma Machine                                 *")
    print("*                                                                              *")
    print("*                            For when you have                                 *")
    print("*                            something that needs                              *")
    print("*                            hiding or cracking!                               *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                    Programmers: CIS220 Class Fall 2019                       *")
    print("*                                                                              *")
    print("*                           Press Enter to continue                            *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("*                                                                              *")
    print("********************************************************************************")
    sel = input("")
    import MAIN
    MAIN.getOption("Home")
    return sel


def home():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("")			   	      
    print("                         Welcome to the Enigma Machine!")
    print("                         This is the software version of")
    print("                         the Enigma Machine used in WWII.")
    print("                         Choose your options below to try.")
    print("")
    print("")
    print("")
    print("                     Encryption [1]             Decryption [2]")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel


def menu():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Menu"))
    print("")
    print("                             Home                 1")
    print("                             Encryption           2")
    print("                             Decryption           3")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel


def setting():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Setting "))
    print("")
    print("			    Change Plug Board	    1")
    print("			    Change Key		    2")
    print("					")
    print("					")
    print("						")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel


def settingPlugBoard():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Plug Board"))
    print("")
    print("		     To change your Plug Board please enter ")
    print("		     your new Plug Board name at the bottom. ")
    print("			    ")
    print("			Thank You    ")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Enter your new Plug Board name here: ")
    return sel


def settingKey():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Key"))
    print("")
    print("{:^80}".format("Enter your key below"))
    print("{:^80}".format("with this format: #-#-#"))
    print("{:^80}".format("The range is from 1 to 665"))
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    key = input("Enter Key:    ")
    key = key.split("-")
    temp = []
    for i in key:
        i = i.lstrip("0")
        temp.append(i)
    key = '-'.join(temp)
    from checkKey import checkKey
    checkKey(key, "Decryption")
    return key


def helpScr():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Help"))
    print("")
    print("{:^80}".format("Choose Options             1"))
    print("{:^80}".format("Key Format                 2"))
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel


def helpOption():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Help"))
    print("")
    print("             Choose option:")
    print("                General options are given on top of each screen.")
    print("                Additional options display inside the screens.")
    print("                To choose the option, enter the given option.")
    print("                Example: Help 0")
    print("                   0 is the option for help")
    print("                   enter 0 to get help")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel


def helpKey():
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Help"))
    print("")
    print("             Key Format:")
    print("                The key format is #-#-#")
    print("                Each \"#\" is represent a digit of the key.")
    print("                The range is from 1 to 665.")
    print("                Each key digit need to be separate by \"-\".")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    sel = input("Choose an option to proceed: ")
    return sel


def encryptionKey():
    from generateKey import getKey
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Encryption"))
    print("")
    print("{:^80}".format("Enter your key in this format: #-#-#"))
    print("{:^80}".format("The range is from 1 to 665"))
    print("{:^80}".format("or hit Enter to generate key"))
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    key = input("Enter Key:    ")
    if key == '':
        key = getKey()
    key = key.split("-")
    temp = []
    for i in key:
        i = i.lstrip("0")
        temp.append(i)
    key = '-'.join(temp)
    from checkKey import checkKey
    checkKey(key, "Encryption")

    return key


def encryption():
    key = encryptionKey()
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Encryption"))
    print("")
    print("{:^80}".format("Enter your message below"))
    print("{:^80}".format("Key: " + key))
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    message = input("Enter Message:  ")
    from checkDoc import checkDoc
    checkDoc(message, "Encryption")
    return message, key


def decryption():
    key = settingKey()
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Decryption"))
    print("")
    print("{:^80}".format("Enter your message below"))
    print("{:^80}".format("Key: " + key))
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    message = input("Enter Message:  ")
    from checkDoc import checkDoc
    checkDoc(message, "Decryption")
    return message, key


def message(doc, key, end):
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Message"))
    print("{:^80}".format("Key: " + key))
    print("")
    mtyLine = 11 - len(doc)
    for i in doc:
        print(i, end='')
    for i in range(mtyLine):
        print("")
    print("")
    print("")
    sel = input("{}".format(end))
    return sel


def error(log):
    print("CIS220 Class Fall 2019                                 Help 0 | About i | Menu x")
    print("")
    print("")
    print("")
    print("{:^80}".format("Enigma Machine"))
    print("")
    print("")
    print("{:^80}".format("Error"))
    print("")
    print("")
    print("{:^80}".format(log))
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    input("Hit Enter to go back")

